name: ci

on:
  push:
    branches:
      - '**'
  # pull_request:
  #   branches:
  #     - '**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mysql-version: ['5.7', '8.0', '8.2']
    name: mysql-version_${{ matrix.mysql-version }}_test

    steps:
      - uses: actions/checkout@v3

      - name: Setup MySQL Server
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: ${{ matrix.mysql-version }}
          host port: 3306
          container port: 3306
          mysql root password: ''

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Initialize database
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -u root < tests/sql/1_schema.sql
          mysql -h 127.0.0.1 -u root < tests/sql/2_data.sql

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Server start
        run: yarn express &

      - name: Wait for server
        run: curl --retry 10 --retry-connrefused --retry-delay 5 --retry-max-time 60 http://localhost:3000/healthcheck

      - name: Test
        run: yarn test
